//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.04 at 02:26:34 PM CEST 
//


package de.openms.consensusXML;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="rt" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="mz" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="it" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "centroid")
public class Centroid {

    @XmlAttribute(required = true)
    protected double rt;
    @XmlAttribute(required = true)
    protected double mz;
    @XmlAttribute(required = true)
    protected double it;

    /**
     * Gets the value of the rt property.
     * 
     */
    public double getRt() {
        return rt;
    }

    /**
     * Sets the value of the rt property.
     * 
     */
    public void setRt(double value) {
        this.rt = value;
    }

    /**
     * Gets the value of the mz property.
     * 
     */
    public double getMz() {
        return mz;
    }

    /**
     * Sets the value of the mz property.
     * 
     */
    public void setMz(double value) {
        this.mz = value;
    }

    /**
     * Gets the value of the it property.
     * 
     */
    public double getIt() {
        return it;
    }

    /**
     * Sets the value of the it property.
     * 
     */
    public void setIt(double value) {
        this.it = value;
    }

}
