//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.04 at 02:26:34 PM CEST 
//


package de.openms.consensusXML;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.openms.consensusXML package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.openms.consensusXML
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ConsensusElementList }
     * 
     */
    public ConsensusElementList createConsensusElementList() {
        return new ConsensusElementList();
    }

    /**
     * Create an instance of {@link ConsensusXML.IdentificationRun.ProteinIdentification.ProteinHit }
     * 
     */
    public ConsensusXML.IdentificationRun.ProteinIdentification.ProteinHit createConsensusXMLIdentificationRunProteinIdentificationProteinHit() {
        return new ConsensusXML.IdentificationRun.ProteinIdentification.ProteinHit();
    }

    /**
     * Create an instance of {@link ConsensusElement }
     * 
     */
    public ConsensusElement createConsensusElement() {
        return new ConsensusElement();
    }

    /**
     * Create an instance of {@link MapList }
     * 
     */
    public MapList createMapList() {
        return new MapList();
    }

    /**
     * Create an instance of {@link ConsensusXML.DataProcessing.ProcessingAction }
     * 
     */
    public ConsensusXML.DataProcessing.ProcessingAction createConsensusXMLDataProcessingProcessingAction() {
        return new ConsensusXML.DataProcessing.ProcessingAction();
    }

    /**
     * Create an instance of {@link ConsensusXML.IdentificationRun.ProteinIdentification }
     * 
     */
    public ConsensusXML.IdentificationRun.ProteinIdentification createConsensusXMLIdentificationRunProteinIdentification() {
        return new ConsensusXML.IdentificationRun.ProteinIdentification();
    }

    /**
     * Create an instance of {@link ConsensusXML.DataProcessing.UserParam }
     * 
     */
    public ConsensusXML.DataProcessing.UserParam createConsensusXMLDataProcessingUserParam() {
        return new ConsensusXML.DataProcessing.UserParam();
    }

    /**
     * Create an instance of {@link ConsensusXML.IdentificationRun.SearchParameters.VariableModification }
     * 
     */
    public ConsensusXML.IdentificationRun.SearchParameters.VariableModification createConsensusXMLIdentificationRunSearchParametersVariableModification() {
        return new ConsensusXML.IdentificationRun.SearchParameters.VariableModification();
    }

    /**
     * Create an instance of {@link ConsensusXML.IdentificationRun.SearchParameters.FixedModification }
     * 
     */
    public ConsensusXML.IdentificationRun.SearchParameters.FixedModification createConsensusXMLIdentificationRunSearchParametersFixedModification() {
        return new ConsensusXML.IdentificationRun.SearchParameters.FixedModification();
    }

    /**
     * Create an instance of {@link ConsensusXML.DataProcessing.Software }
     * 
     */
    public ConsensusXML.DataProcessing.Software createConsensusXMLDataProcessingSoftware() {
        return new ConsensusXML.DataProcessing.Software();
    }

    /**
     * Create an instance of {@link Map }
     * 
     */
    public Map createMap() {
        return new Map();
    }

    /**
     * Create an instance of {@link ConsensusXML.UnassignedPeptideIdentification }
     * 
     */
    public ConsensusXML.UnassignedPeptideIdentification createConsensusXMLUnassignedPeptideIdentification() {
        return new ConsensusXML.UnassignedPeptideIdentification();
    }

    /**
     * Create an instance of {@link GroupedElementList }
     * 
     */
    public GroupedElementList createGroupedElementList() {
        return new GroupedElementList();
    }

    /**
     * Create an instance of {@link ConsensusXML.UnassignedPeptideIdentification.PeptideHit }
     * 
     */
    public ConsensusXML.UnassignedPeptideIdentification.PeptideHit createConsensusXMLUnassignedPeptideIdentificationPeptideHit() {
        return new ConsensusXML.UnassignedPeptideIdentification.PeptideHit();
    }

    /**
     * Create an instance of {@link ConsensusXML.IdentificationRun }
     * 
     */
    public ConsensusXML.IdentificationRun createConsensusXMLIdentificationRun() {
        return new ConsensusXML.IdentificationRun();
    }

    /**
     * Create an instance of {@link ConsensusXML.IdentificationRun.SearchParameters }
     * 
     */
    public ConsensusXML.IdentificationRun.SearchParameters createConsensusXMLIdentificationRunSearchParameters() {
        return new ConsensusXML.IdentificationRun.SearchParameters();
    }

    /**
     * Create an instance of {@link ConsensusXML.DataProcessing }
     * 
     */
    public ConsensusXML.DataProcessing createConsensusXMLDataProcessing() {
        return new ConsensusXML.DataProcessing();
    }

    /**
     * Create an instance of {@link ConsensusXML }
     * 
     */
    public ConsensusXML createConsensusXML() {
        return new ConsensusXML();
    }

    /**
     * Create an instance of {@link ConsensusElement.PeptideIdentification }
     * 
     */
    public ConsensusElement.PeptideIdentification createConsensusElementPeptideIdentification() {
        return new ConsensusElement.PeptideIdentification();
    }

    /**
     * Create an instance of {@link de.openms.consensusXML.UserParam }
     * 
     */
    public de.openms.consensusXML.UserParam createUserParam() {
        return new de.openms.consensusXML.UserParam();
    }

    /**
     * Create an instance of {@link ConsensusElement.PeptideIdentification.PeptideHit }
     * 
     */
    public ConsensusElement.PeptideIdentification.PeptideHit createConsensusElementPeptideIdentificationPeptideHit() {
        return new ConsensusElement.PeptideIdentification.PeptideHit();
    }

    /**
     * Create an instance of {@link Centroid }
     * 
     */
    public Centroid createCentroid() {
        return new Centroid();
    }

    /**
     * Create an instance of {@link Element }
     * 
     */
    public Element createElement() {
        return new Element();
    }

}
