//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.04 at 02:26:34 PM CEST 
//


package de.openms.consensusXML;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="userParam" type="{}userParam" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="dataProcessing" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="software">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="processingAction" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="userParam" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{}userParam">
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="completion_time" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="IdentificationRun" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="SearchParameters">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="FixedModification" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence minOccurs="0">
 *                                       &lt;element name="userParam" type="{}userParam" maxOccurs="unbounded" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="name" use="required">
 *                                       &lt;simpleType>
 *                                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                           &lt;minLength value="1"/>
 *                                         &lt;/restriction>
 *                                       &lt;/simpleType>
 *                                     &lt;/attribute>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="VariableModification" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence minOccurs="0">
 *                                       &lt;element name="userParam" type="{}userParam" maxOccurs="unbounded" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="name" use="required">
 *                                       &lt;simpleType>
 *                                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                           &lt;minLength value="1"/>
 *                                         &lt;/restriction>
 *                                       &lt;/simpleType>
 *                                     &lt;/attribute>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="userParam" type="{}userParam" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="db" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="db_version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="taxonomy" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="mass_type" use="required" type="{}MassType" />
 *                           &lt;attribute name="charges" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="enzyme" type="{}DigestionEnzyme" />
 *                           &lt;attribute name="missed_cleavages" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *                           &lt;attribute name="precursor_peak_tolerance" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                           &lt;attribute name="peak_mass_tolerance" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="ProteinIdentification" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ProteinHit" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence minOccurs="0">
 *                                       &lt;element name="userParam" type="{}userParam" maxOccurs="unbounded" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *                                     &lt;attribute name="accession" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="score" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                                     &lt;attribute name="sequence" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="userParam" type="{}userParam" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="score_type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="higher_score_better" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                           &lt;attribute name="significance_threshold" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *                 &lt;attribute name="search_engine" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="search_engine_version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="date" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="UnassignedPeptideIdentification" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="PeptideHit" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence minOccurs="0">
 *                             &lt;element name="userParam" type="{}userParam" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="sequence" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="charge" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                           &lt;attribute name="score" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                           &lt;attribute name="aa_before">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;minLength value="0"/>
 *                                 &lt;maxLength value="1"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="aa_after">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;minLength value="0"/>
 *                                 &lt;maxLength value="1"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="protein_refs" type="{http://www.w3.org/2001/XMLSchema}IDREFS" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="userParam" type="{}userParam" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="identification_run_ref" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *                 &lt;attribute name="score_type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="higher_score_better" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                 &lt;attribute name="significance_threshold" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                 &lt;attribute name="spectrum_reference" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *                 &lt;attribute name="RT" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                 &lt;attribute name="MZ" type="{http://www.w3.org/2001/XMLSchema}float" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{}mapList"/>
 *         &lt;element ref="{}consensusElementList"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="experiment_type">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="labeled_MS1"/>
 *             &lt;enumeration value="labeled_MS2"/>
 *             &lt;enumeration value="icat"/>
 *             &lt;enumeration value="itraq"/>
 *             &lt;enumeration value="silac"/>
 *             &lt;enumeration value="label-free"/>
 *             &lt;enumeration value="other"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="document_id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "userParam",
    "dataProcessing",
    "identificationRun",
    "unassignedPeptideIdentification",
    "mapList",
    "consensusElementList"
})
@XmlRootElement(name = "consensusXML")
public class ConsensusXML {

    protected List<de.openms.consensusXML.UserParam> userParam;
    protected List<ConsensusXML.DataProcessing> dataProcessing;
    @XmlElement(name = "IdentificationRun")
    protected List<ConsensusXML.IdentificationRun> identificationRun;
    @XmlElement(name = "UnassignedPeptideIdentification")
    protected List<ConsensusXML.UnassignedPeptideIdentification> unassignedPeptideIdentification;
    @XmlElement(required = true)
    protected MapList mapList;
    @XmlElement(required = true)
    protected ConsensusElementList consensusElementList;
    @XmlAttribute
    protected Float version;
    @XmlAttribute(name = "experiment_type")
    protected String experimentType;
    @XmlAttribute(name = "document_id")
    protected String documentId;
    @XmlAttribute
    protected String id;

    /**
     * Gets the value of the userParam property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the userParam property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUserParam().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link de.openms.consensusXML.UserParam }
     * 
     * 
     */
    public List<de.openms.consensusXML.UserParam> getUserParam() {
        if (userParam == null) {
            userParam = new ArrayList<de.openms.consensusXML.UserParam>();
        }
        return this.userParam;
    }

    /**
     * Gets the value of the dataProcessing property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dataProcessing property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDataProcessing().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConsensusXML.DataProcessing }
     * 
     * 
     */
    public List<ConsensusXML.DataProcessing> getDataProcessing() {
        if (dataProcessing == null) {
            dataProcessing = new ArrayList<ConsensusXML.DataProcessing>();
        }
        return this.dataProcessing;
    }

    /**
     * Gets the value of the identificationRun property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the identificationRun property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdentificationRun().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConsensusXML.IdentificationRun }
     * 
     * 
     */
    public List<ConsensusXML.IdentificationRun> getIdentificationRun() {
        if (identificationRun == null) {
            identificationRun = new ArrayList<ConsensusXML.IdentificationRun>();
        }
        return this.identificationRun;
    }

    /**
     * Gets the value of the unassignedPeptideIdentification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the unassignedPeptideIdentification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUnassignedPeptideIdentification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConsensusXML.UnassignedPeptideIdentification }
     * 
     * 
     */
    public List<ConsensusXML.UnassignedPeptideIdentification> getUnassignedPeptideIdentification() {
        if (unassignedPeptideIdentification == null) {
            unassignedPeptideIdentification = new ArrayList<ConsensusXML.UnassignedPeptideIdentification>();
        }
        return this.unassignedPeptideIdentification;
    }

    /**
     * Gets the value of the mapList property.
     * 
     * @return
     *     possible object is
     *     {@link MapList }
     *     
     */
    public MapList getMapList() {
        return mapList;
    }

    /**
     * Sets the value of the mapList property.
     * 
     * @param value
     *     allowed object is
     *     {@link MapList }
     *     
     */
    public void setMapList(MapList value) {
        this.mapList = value;
    }

    /**
     * Gets the value of the consensusElementList property.
     * 
     * @return
     *     possible object is
     *     {@link ConsensusElementList }
     *     
     */
    public ConsensusElementList getConsensusElementList() {
        return consensusElementList;
    }

    /**
     * Sets the value of the consensusElementList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConsensusElementList }
     *     
     */
    public void setConsensusElementList(ConsensusElementList value) {
        this.consensusElementList = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setVersion(Float value) {
        this.version = value;
    }

    /**
     * Gets the value of the experimentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExperimentType() {
        return experimentType;
    }

    /**
     * Sets the value of the experimentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExperimentType(String value) {
        this.experimentType = value;
    }

    /**
     * Gets the value of the documentId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentId() {
        return documentId;
    }

    /**
     * Sets the value of the documentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentId(String value) {
        this.documentId = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="software">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="processingAction" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="userParam" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{}userParam">
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="completion_time" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "software",
        "processingAction",
        "userParam"
    })
    public static class DataProcessing {

        @XmlElement(required = true)
        protected ConsensusXML.DataProcessing.Software software;
        protected List<ConsensusXML.DataProcessing.ProcessingAction> processingAction;
        protected List<ConsensusXML.DataProcessing.UserParam> userParam;
        @XmlAttribute(name = "completion_time", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar completionTime;

        /**
         * Gets the value of the software property.
         * 
         * @return
         *     possible object is
         *     {@link ConsensusXML.DataProcessing.Software }
         *     
         */
        public ConsensusXML.DataProcessing.Software getSoftware() {
            return software;
        }

        /**
         * Sets the value of the software property.
         * 
         * @param value
         *     allowed object is
         *     {@link ConsensusXML.DataProcessing.Software }
         *     
         */
        public void setSoftware(ConsensusXML.DataProcessing.Software value) {
            this.software = value;
        }

        /**
         * Gets the value of the processingAction property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the processingAction property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProcessingAction().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ConsensusXML.DataProcessing.ProcessingAction }
         * 
         * 
         */
        public List<ConsensusXML.DataProcessing.ProcessingAction> getProcessingAction() {
            if (processingAction == null) {
                processingAction = new ArrayList<ConsensusXML.DataProcessing.ProcessingAction>();
            }
            return this.processingAction;
        }

        /**
         * Gets the value of the userParam property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the userParam property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUserParam().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ConsensusXML.DataProcessing.UserParam }
         * 
         * 
         */
        public List<ConsensusXML.DataProcessing.UserParam> getUserParam() {
            if (userParam == null) {
                userParam = new ArrayList<ConsensusXML.DataProcessing.UserParam>();
            }
            return this.userParam;
        }

        /**
         * Gets the value of the completionTime property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getCompletionTime() {
            return completionTime;
        }

        /**
         * Sets the value of the completionTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setCompletionTime(XMLGregorianCalendar value) {
            this.completionTime = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class ProcessingAction {

            @XmlAttribute(required = true)
            protected String name;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Software {

            @XmlAttribute(required = true)
            protected String name;
            @XmlAttribute(required = true)
            protected String version;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the version property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVersion() {
                return version;
            }

            /**
             * Sets the value of the version property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVersion(String value) {
                this.version = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{}userParam">
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class UserParam
            extends de.openms.consensusXML.UserParam
        {


        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="SearchParameters">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="FixedModification" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence minOccurs="0">
     *                             &lt;element name="userParam" type="{}userParam" maxOccurs="unbounded" minOccurs="0"/>
     *                           &lt;/sequence>
     *                           &lt;attribute name="name" use="required">
     *                             &lt;simpleType>
     *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                 &lt;minLength value="1"/>
     *                               &lt;/restriction>
     *                             &lt;/simpleType>
     *                           &lt;/attribute>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="VariableModification" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence minOccurs="0">
     *                             &lt;element name="userParam" type="{}userParam" maxOccurs="unbounded" minOccurs="0"/>
     *                           &lt;/sequence>
     *                           &lt;attribute name="name" use="required">
     *                             &lt;simpleType>
     *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                 &lt;minLength value="1"/>
     *                               &lt;/restriction>
     *                             &lt;/simpleType>
     *                           &lt;/attribute>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="userParam" type="{}userParam" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="db" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="db_version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="taxonomy" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="mass_type" use="required" type="{}MassType" />
     *                 &lt;attribute name="charges" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="enzyme" type="{}DigestionEnzyme" />
     *                 &lt;attribute name="missed_cleavages" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
     *                 &lt;attribute name="precursor_peak_tolerance" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
     *                 &lt;attribute name="peak_mass_tolerance" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="ProteinIdentification" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ProteinHit" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence minOccurs="0">
     *                             &lt;element name="userParam" type="{}userParam" maxOccurs="unbounded" minOccurs="0"/>
     *                           &lt;/sequence>
     *                           &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
     *                           &lt;attribute name="accession" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="score" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
     *                           &lt;attribute name="sequence" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="userParam" type="{}userParam" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="score_type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="higher_score_better" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *                 &lt;attribute name="significance_threshold" type="{http://www.w3.org/2001/XMLSchema}float" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
     *       &lt;attribute name="search_engine" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="search_engine_version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="date" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "searchParameters",
        "proteinIdentification"
    })
    public static class IdentificationRun {

        @XmlElement(name = "SearchParameters", required = true)
        protected ConsensusXML.IdentificationRun.SearchParameters searchParameters;
        @XmlElement(name = "ProteinIdentification")
        protected ConsensusXML.IdentificationRun.ProteinIdentification proteinIdentification;
        @XmlAttribute(required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlID
        @XmlSchemaType(name = "ID")
        protected String id;
        @XmlAttribute(name = "search_engine", required = true)
        protected String searchEngine;
        @XmlAttribute(name = "search_engine_version", required = true)
        protected String searchEngineVersion;
        @XmlAttribute(required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar date;

        /**
         * Gets the value of the searchParameters property.
         * 
         * @return
         *     possible object is
         *     {@link ConsensusXML.IdentificationRun.SearchParameters }
         *     
         */
        public ConsensusXML.IdentificationRun.SearchParameters getSearchParameters() {
            return searchParameters;
        }

        /**
         * Sets the value of the searchParameters property.
         * 
         * @param value
         *     allowed object is
         *     {@link ConsensusXML.IdentificationRun.SearchParameters }
         *     
         */
        public void setSearchParameters(ConsensusXML.IdentificationRun.SearchParameters value) {
            this.searchParameters = value;
        }

        /**
         * Gets the value of the proteinIdentification property.
         * 
         * @return
         *     possible object is
         *     {@link ConsensusXML.IdentificationRun.ProteinIdentification }
         *     
         */
        public ConsensusXML.IdentificationRun.ProteinIdentification getProteinIdentification() {
            return proteinIdentification;
        }

        /**
         * Sets the value of the proteinIdentification property.
         * 
         * @param value
         *     allowed object is
         *     {@link ConsensusXML.IdentificationRun.ProteinIdentification }
         *     
         */
        public void setProteinIdentification(ConsensusXML.IdentificationRun.ProteinIdentification value) {
            this.proteinIdentification = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the searchEngine property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSearchEngine() {
            return searchEngine;
        }

        /**
         * Sets the value of the searchEngine property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSearchEngine(String value) {
            this.searchEngine = value;
        }

        /**
         * Gets the value of the searchEngineVersion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSearchEngineVersion() {
            return searchEngineVersion;
        }

        /**
         * Sets the value of the searchEngineVersion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSearchEngineVersion(String value) {
            this.searchEngineVersion = value;
        }

        /**
         * Gets the value of the date property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDate() {
            return date;
        }

        /**
         * Sets the value of the date property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDate(XMLGregorianCalendar value) {
            this.date = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ProteinHit" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence minOccurs="0">
         *                   &lt;element name="userParam" type="{}userParam" maxOccurs="unbounded" minOccurs="0"/>
         *                 &lt;/sequence>
         *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
         *                 &lt;attribute name="accession" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="score" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
         *                 &lt;attribute name="sequence" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="userParam" type="{}userParam" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *       &lt;attribute name="score_type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="higher_score_better" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *       &lt;attribute name="significance_threshold" type="{http://www.w3.org/2001/XMLSchema}float" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "proteinHit",
            "userParam"
        })
        public static class ProteinIdentification {

            @XmlElement(name = "ProteinHit")
            protected List<ConsensusXML.IdentificationRun.ProteinIdentification.ProteinHit> proteinHit;
            protected List<de.openms.consensusXML.UserParam> userParam;
            @XmlAttribute(name = "score_type", required = true)
            protected String scoreType;
            @XmlAttribute(name = "higher_score_better", required = true)
            protected boolean higherScoreBetter;
            @XmlAttribute(name = "significance_threshold")
            protected Float significanceThreshold;

            /**
             * Gets the value of the proteinHit property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the proteinHit property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getProteinHit().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link ConsensusXML.IdentificationRun.ProteinIdentification.ProteinHit }
             * 
             * 
             */
            public List<ConsensusXML.IdentificationRun.ProteinIdentification.ProteinHit> getProteinHit() {
                if (proteinHit == null) {
                    proteinHit = new ArrayList<ConsensusXML.IdentificationRun.ProteinIdentification.ProteinHit>();
                }
                return this.proteinHit;
            }

            /**
             * Gets the value of the userParam property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the userParam property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getUserParam().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link de.openms.consensusXML.UserParam }
             * 
             * 
             */
            public List<de.openms.consensusXML.UserParam> getUserParam() {
                if (userParam == null) {
                    userParam = new ArrayList<de.openms.consensusXML.UserParam>();
                }
                return this.userParam;
            }

            /**
             * Gets the value of the scoreType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getScoreType() {
                return scoreType;
            }

            /**
             * Sets the value of the scoreType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setScoreType(String value) {
                this.scoreType = value;
            }

            /**
             * Gets the value of the higherScoreBetter property.
             * 
             */
            public boolean isHigherScoreBetter() {
                return higherScoreBetter;
            }

            /**
             * Sets the value of the higherScoreBetter property.
             * 
             */
            public void setHigherScoreBetter(boolean value) {
                this.higherScoreBetter = value;
            }

            /**
             * Gets the value of the significanceThreshold property.
             * 
             * @return
             *     possible object is
             *     {@link Float }
             *     
             */
            public Float getSignificanceThreshold() {
                return significanceThreshold;
            }

            /**
             * Sets the value of the significanceThreshold property.
             * 
             * @param value
             *     allowed object is
             *     {@link Float }
             *     
             */
            public void setSignificanceThreshold(Float value) {
                this.significanceThreshold = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence minOccurs="0">
             *         &lt;element name="userParam" type="{}userParam" maxOccurs="unbounded" minOccurs="0"/>
             *       &lt;/sequence>
             *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
             *       &lt;attribute name="accession" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="score" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
             *       &lt;attribute name="sequence" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "userParam"
            })
            public static class ProteinHit {

                protected List<de.openms.consensusXML.UserParam> userParam;
                @XmlAttribute(required = true)
                @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
                @XmlID
                @XmlSchemaType(name = "ID")
                protected String id;
                @XmlAttribute(required = true)
                protected String accession;
                @XmlAttribute(required = true)
                protected float score;
                @XmlAttribute
                protected String sequence;

                /**
                 * Gets the value of the userParam property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the userParam property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getUserParam().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link de.openms.consensusXML.UserParam }
                 * 
                 * 
                 */
                public List<de.openms.consensusXML.UserParam> getUserParam() {
                    if (userParam == null) {
                        userParam = new ArrayList<de.openms.consensusXML.UserParam>();
                    }
                    return this.userParam;
                }

                /**
                 * Gets the value of the id property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getId() {
                    return id;
                }

                /**
                 * Sets the value of the id property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setId(String value) {
                    this.id = value;
                }

                /**
                 * Gets the value of the accession property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAccession() {
                    return accession;
                }

                /**
                 * Sets the value of the accession property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAccession(String value) {
                    this.accession = value;
                }

                /**
                 * Gets the value of the score property.
                 * 
                 */
                public float getScore() {
                    return score;
                }

                /**
                 * Sets the value of the score property.
                 * 
                 */
                public void setScore(float value) {
                    this.score = value;
                }

                /**
                 * Gets the value of the sequence property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSequence() {
                    return sequence;
                }

                /**
                 * Sets the value of the sequence property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSequence(String value) {
                    this.sequence = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="FixedModification" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence minOccurs="0">
         *                   &lt;element name="userParam" type="{}userParam" maxOccurs="unbounded" minOccurs="0"/>
         *                 &lt;/sequence>
         *                 &lt;attribute name="name" use="required">
         *                   &lt;simpleType>
         *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                       &lt;minLength value="1"/>
         *                     &lt;/restriction>
         *                   &lt;/simpleType>
         *                 &lt;/attribute>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="VariableModification" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence minOccurs="0">
         *                   &lt;element name="userParam" type="{}userParam" maxOccurs="unbounded" minOccurs="0"/>
         *                 &lt;/sequence>
         *                 &lt;attribute name="name" use="required">
         *                   &lt;simpleType>
         *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                       &lt;minLength value="1"/>
         *                     &lt;/restriction>
         *                   &lt;/simpleType>
         *                 &lt;/attribute>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="userParam" type="{}userParam" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *       &lt;attribute name="db" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="db_version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="taxonomy" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="mass_type" use="required" type="{}MassType" />
         *       &lt;attribute name="charges" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="enzyme" type="{}DigestionEnzyme" />
         *       &lt;attribute name="missed_cleavages" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
         *       &lt;attribute name="precursor_peak_tolerance" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
         *       &lt;attribute name="peak_mass_tolerance" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "fixedModification",
            "variableModification",
            "userParam"
        })
        public static class SearchParameters {

            @XmlElement(name = "FixedModification")
            protected List<ConsensusXML.IdentificationRun.SearchParameters.FixedModification> fixedModification;
            @XmlElement(name = "VariableModification")
            protected List<ConsensusXML.IdentificationRun.SearchParameters.VariableModification> variableModification;
            protected List<de.openms.consensusXML.UserParam> userParam;
            @XmlAttribute(required = true)
            protected String db;
            @XmlAttribute(name = "db_version", required = true)
            protected String dbVersion;
            @XmlAttribute
            protected String taxonomy;
            @XmlAttribute(name = "mass_type", required = true)
            protected MassType massType;
            @XmlAttribute(required = true)
            protected String charges;
            @XmlAttribute
            protected DigestionEnzyme enzyme;
            @XmlAttribute(name = "missed_cleavages")
            @XmlSchemaType(name = "unsignedInt")
            protected Long missedCleavages;
            @XmlAttribute(name = "precursor_peak_tolerance", required = true)
            protected float precursorPeakTolerance;
            @XmlAttribute(name = "peak_mass_tolerance", required = true)
            protected float peakMassTolerance;

            /**
             * Gets the value of the fixedModification property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the fixedModification property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getFixedModification().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link ConsensusXML.IdentificationRun.SearchParameters.FixedModification }
             * 
             * 
             */
            public List<ConsensusXML.IdentificationRun.SearchParameters.FixedModification> getFixedModification() {
                if (fixedModification == null) {
                    fixedModification = new ArrayList<ConsensusXML.IdentificationRun.SearchParameters.FixedModification>();
                }
                return this.fixedModification;
            }

            /**
             * Gets the value of the variableModification property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the variableModification property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getVariableModification().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link ConsensusXML.IdentificationRun.SearchParameters.VariableModification }
             * 
             * 
             */
            public List<ConsensusXML.IdentificationRun.SearchParameters.VariableModification> getVariableModification() {
                if (variableModification == null) {
                    variableModification = new ArrayList<ConsensusXML.IdentificationRun.SearchParameters.VariableModification>();
                }
                return this.variableModification;
            }

            /**
             * Gets the value of the userParam property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the userParam property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getUserParam().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link de.openms.consensusXML.UserParam }
             * 
             * 
             */
            public List<de.openms.consensusXML.UserParam> getUserParam() {
                if (userParam == null) {
                    userParam = new ArrayList<de.openms.consensusXML.UserParam>();
                }
                return this.userParam;
            }

            /**
             * Gets the value of the db property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDb() {
                return db;
            }

            /**
             * Sets the value of the db property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDb(String value) {
                this.db = value;
            }

            /**
             * Gets the value of the dbVersion property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDbVersion() {
                return dbVersion;
            }

            /**
             * Sets the value of the dbVersion property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDbVersion(String value) {
                this.dbVersion = value;
            }

            /**
             * Gets the value of the taxonomy property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTaxonomy() {
                return taxonomy;
            }

            /**
             * Sets the value of the taxonomy property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTaxonomy(String value) {
                this.taxonomy = value;
            }

            /**
             * Gets the value of the massType property.
             * 
             * @return
             *     possible object is
             *     {@link MassType }
             *     
             */
            public MassType getMassType() {
                return massType;
            }

            /**
             * Sets the value of the massType property.
             * 
             * @param value
             *     allowed object is
             *     {@link MassType }
             *     
             */
            public void setMassType(MassType value) {
                this.massType = value;
            }

            /**
             * Gets the value of the charges property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCharges() {
                return charges;
            }

            /**
             * Sets the value of the charges property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCharges(String value) {
                this.charges = value;
            }

            /**
             * Gets the value of the enzyme property.
             * 
             * @return
             *     possible object is
             *     {@link DigestionEnzyme }
             *     
             */
            public DigestionEnzyme getEnzyme() {
                return enzyme;
            }

            /**
             * Sets the value of the enzyme property.
             * 
             * @param value
             *     allowed object is
             *     {@link DigestionEnzyme }
             *     
             */
            public void setEnzyme(DigestionEnzyme value) {
                this.enzyme = value;
            }

            /**
             * Gets the value of the missedCleavages property.
             * 
             * @return
             *     possible object is
             *     {@link Long }
             *     
             */
            public Long getMissedCleavages() {
                return missedCleavages;
            }

            /**
             * Sets the value of the missedCleavages property.
             * 
             * @param value
             *     allowed object is
             *     {@link Long }
             *     
             */
            public void setMissedCleavages(Long value) {
                this.missedCleavages = value;
            }

            /**
             * Gets the value of the precursorPeakTolerance property.
             * 
             */
            public float getPrecursorPeakTolerance() {
                return precursorPeakTolerance;
            }

            /**
             * Sets the value of the precursorPeakTolerance property.
             * 
             */
            public void setPrecursorPeakTolerance(float value) {
                this.precursorPeakTolerance = value;
            }

            /**
             * Gets the value of the peakMassTolerance property.
             * 
             */
            public float getPeakMassTolerance() {
                return peakMassTolerance;
            }

            /**
             * Sets the value of the peakMassTolerance property.
             * 
             */
            public void setPeakMassTolerance(float value) {
                this.peakMassTolerance = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence minOccurs="0">
             *         &lt;element name="userParam" type="{}userParam" maxOccurs="unbounded" minOccurs="0"/>
             *       &lt;/sequence>
             *       &lt;attribute name="name" use="required">
             *         &lt;simpleType>
             *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *             &lt;minLength value="1"/>
             *           &lt;/restriction>
             *         &lt;/simpleType>
             *       &lt;/attribute>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "userParam"
            })
            public static class FixedModification {

                protected List<de.openms.consensusXML.UserParam> userParam;
                @XmlAttribute(required = true)
                protected String name;

                /**
                 * Gets the value of the userParam property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the userParam property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getUserParam().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link de.openms.consensusXML.UserParam }
                 * 
                 * 
                 */
                public List<de.openms.consensusXML.UserParam> getUserParam() {
                    if (userParam == null) {
                        userParam = new ArrayList<de.openms.consensusXML.UserParam>();
                    }
                    return this.userParam;
                }

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence minOccurs="0">
             *         &lt;element name="userParam" type="{}userParam" maxOccurs="unbounded" minOccurs="0"/>
             *       &lt;/sequence>
             *       &lt;attribute name="name" use="required">
             *         &lt;simpleType>
             *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *             &lt;minLength value="1"/>
             *           &lt;/restriction>
             *         &lt;/simpleType>
             *       &lt;/attribute>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "userParam"
            })
            public static class VariableModification {

                protected List<de.openms.consensusXML.UserParam> userParam;
                @XmlAttribute(required = true)
                protected String name;

                /**
                 * Gets the value of the userParam property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the userParam property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getUserParam().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link de.openms.consensusXML.UserParam }
                 * 
                 * 
                 */
                public List<de.openms.consensusXML.UserParam> getUserParam() {
                    if (userParam == null) {
                        userParam = new ArrayList<de.openms.consensusXML.UserParam>();
                    }
                    return this.userParam;
                }

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="PeptideHit" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence minOccurs="0">
     *                   &lt;element name="userParam" type="{}userParam" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="sequence" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="charge" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *                 &lt;attribute name="score" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
     *                 &lt;attribute name="aa_before">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;minLength value="0"/>
     *                       &lt;maxLength value="1"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="aa_after">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;minLength value="0"/>
     *                       &lt;maxLength value="1"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="protein_refs" type="{http://www.w3.org/2001/XMLSchema}IDREFS" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="userParam" type="{}userParam" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="identification_run_ref" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
     *       &lt;attribute name="score_type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="higher_score_better" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *       &lt;attribute name="significance_threshold" type="{http://www.w3.org/2001/XMLSchema}float" />
     *       &lt;attribute name="spectrum_reference" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
     *       &lt;attribute name="RT" type="{http://www.w3.org/2001/XMLSchema}float" />
     *       &lt;attribute name="MZ" type="{http://www.w3.org/2001/XMLSchema}float" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "peptideHit",
        "userParam"
    })
    public static class UnassignedPeptideIdentification {

        @XmlElement(name = "PeptideHit")
        protected List<ConsensusXML.UnassignedPeptideIdentification.PeptideHit> peptideHit;
        protected List<de.openms.consensusXML.UserParam> userParam;
        @XmlAttribute(name = "identification_run_ref", required = true)
        @XmlIDREF
        @XmlSchemaType(name = "IDREF")
        protected Object identificationRunRef;
        @XmlAttribute(name = "score_type", required = true)
        protected String scoreType;
        @XmlAttribute(name = "higher_score_better", required = true)
        protected boolean higherScoreBetter;
        @XmlAttribute(name = "significance_threshold")
        protected Float significanceThreshold;
        @XmlAttribute(name = "spectrum_reference")
        @XmlSchemaType(name = "unsignedInt")
        protected Long spectrumReference;
        @XmlAttribute(name = "RT")
        protected Float rt;
        @XmlAttribute(name = "MZ")
        protected Float mz;

        /**
         * Gets the value of the peptideHit property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the peptideHit property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPeptideHit().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ConsensusXML.UnassignedPeptideIdentification.PeptideHit }
         * 
         * 
         */
        public List<ConsensusXML.UnassignedPeptideIdentification.PeptideHit> getPeptideHit() {
            if (peptideHit == null) {
                peptideHit = new ArrayList<ConsensusXML.UnassignedPeptideIdentification.PeptideHit>();
            }
            return this.peptideHit;
        }

        /**
         * Gets the value of the userParam property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the userParam property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUserParam().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link de.openms.consensusXML.UserParam }
         * 
         * 
         */
        public List<de.openms.consensusXML.UserParam> getUserParam() {
            if (userParam == null) {
                userParam = new ArrayList<de.openms.consensusXML.UserParam>();
            }
            return this.userParam;
        }

        /**
         * Gets the value of the identificationRunRef property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getIdentificationRunRef() {
            return identificationRunRef;
        }

        /**
         * Sets the value of the identificationRunRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setIdentificationRunRef(Object value) {
            this.identificationRunRef = value;
        }

        /**
         * Gets the value of the scoreType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getScoreType() {
            return scoreType;
        }

        /**
         * Sets the value of the scoreType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setScoreType(String value) {
            this.scoreType = value;
        }

        /**
         * Gets the value of the higherScoreBetter property.
         * 
         */
        public boolean isHigherScoreBetter() {
            return higherScoreBetter;
        }

        /**
         * Sets the value of the higherScoreBetter property.
         * 
         */
        public void setHigherScoreBetter(boolean value) {
            this.higherScoreBetter = value;
        }

        /**
         * Gets the value of the significanceThreshold property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getSignificanceThreshold() {
            return significanceThreshold;
        }

        /**
         * Sets the value of the significanceThreshold property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setSignificanceThreshold(Float value) {
            this.significanceThreshold = value;
        }

        /**
         * Gets the value of the spectrumReference property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getSpectrumReference() {
            return spectrumReference;
        }

        /**
         * Sets the value of the spectrumReference property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setSpectrumReference(Long value) {
            this.spectrumReference = value;
        }

        /**
         * Gets the value of the rt property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getRT() {
            return rt;
        }

        /**
         * Sets the value of the rt property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setRT(Float value) {
            this.rt = value;
        }

        /**
         * Gets the value of the mz property.
         * 
         * @return
         *     possible object is
         *     {@link Float }
         *     
         */
        public Float getMZ() {
            return mz;
        }

        /**
         * Sets the value of the mz property.
         * 
         * @param value
         *     allowed object is
         *     {@link Float }
         *     
         */
        public void setMZ(Float value) {
            this.mz = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence minOccurs="0">
         *         &lt;element name="userParam" type="{}userParam" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *       &lt;attribute name="sequence" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="charge" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
         *       &lt;attribute name="score" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
         *       &lt;attribute name="aa_before">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;minLength value="0"/>
         *             &lt;maxLength value="1"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="aa_after">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;minLength value="0"/>
         *             &lt;maxLength value="1"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="protein_refs" type="{http://www.w3.org/2001/XMLSchema}IDREFS" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "userParam"
        })
        public static class PeptideHit {

            protected List<de.openms.consensusXML.UserParam> userParam;
            @XmlAttribute(required = true)
            protected String sequence;
            @XmlAttribute(required = true)
            protected BigInteger charge;
            @XmlAttribute(required = true)
            protected float score;
            @XmlAttribute(name = "aa_before")
            protected String aaBefore;
            @XmlAttribute(name = "aa_after")
            protected String aaAfter;
            @XmlAttribute(name = "protein_refs")
            @XmlIDREF
            @XmlSchemaType(name = "IDREFS")
            protected List<Object> proteinRefs;

            /**
             * Gets the value of the userParam property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the userParam property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getUserParam().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link de.openms.consensusXML.UserParam }
             * 
             * 
             */
            public List<de.openms.consensusXML.UserParam> getUserParam() {
                if (userParam == null) {
                    userParam = new ArrayList<de.openms.consensusXML.UserParam>();
                }
                return this.userParam;
            }

            /**
             * Gets the value of the sequence property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSequence() {
                return sequence;
            }

            /**
             * Sets the value of the sequence property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSequence(String value) {
                this.sequence = value;
            }

            /**
             * Gets the value of the charge property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getCharge() {
                return charge;
            }

            /**
             * Sets the value of the charge property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setCharge(BigInteger value) {
                this.charge = value;
            }

            /**
             * Gets the value of the score property.
             * 
             */
            public float getScore() {
                return score;
            }

            /**
             * Sets the value of the score property.
             * 
             */
            public void setScore(float value) {
                this.score = value;
            }

            /**
             * Gets the value of the aaBefore property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAaBefore() {
                return aaBefore;
            }

            /**
             * Sets the value of the aaBefore property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAaBefore(String value) {
                this.aaBefore = value;
            }

            /**
             * Gets the value of the aaAfter property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAaAfter() {
                return aaAfter;
            }

            /**
             * Sets the value of the aaAfter property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAaAfter(String value) {
                this.aaAfter = value;
            }

            /**
             * Gets the value of the proteinRefs property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the proteinRefs property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getProteinRefs().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Object }
             * 
             * 
             */
            public List<Object> getProteinRefs() {
                if (proteinRefs == null) {
                    proteinRefs = new ArrayList<Object>();
                }
                return this.proteinRefs;
            }

        }

    }

}
